name: Dev Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://jan-bredow.de
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: vps.jan-bredow.de
          key: ${{ secrets.SSH_KEY }}
          script: 'cd /opt/BredowSystems/jb/pkg/ && chmod +x ../.scripts/deploy.sh && ../.scripts/deploy.sh'
